sudo: required
dist: trusty
os:
  - linux

services:
  - docker

script:
  - docker build -f Dockerfile.linux -t buildtest:linux
  - docker run --rm buildtest:linux
  - docker build -f Dockerfile.android -t buildtest:android
  - docker run --rm buildtest:android
