sudo: required
dist: trusty
os:
  - linux

services:
  - docker

script:
  - docker build -f ./.travis/Dockerfile.linux -t buildtest:linux ./.travis
  - docker run --rm buildtest:linux ninja
  - docker build -f ./.travis/Dockerfile.android -t buildtest:android ./.travis
  - docker run --rm buildtest:android ninja
