# Linux build configuration for both native binaries and Android apks

sudo: required
dist: trusty
os:
  - linux

services:
  - docker

env:
  - TARGET=linux
  - TARGET=android

script:
  - docker build -f ./.build-$TARGET.dockerfile -t buildtest:$TARGET .
  - docker run --rm buildtest:$TARGET
