sudo: required
dist: trusty
os:
  - linux

services:
  - docker

script:
  - docker build -f Dockerfile.linux -t buildtest:linux ./.travis
  - docker run --rm buildtest:linux ninja
  - docker build -f Dockerfile.android -t buildtest:android ./.travis
  - docker run --rm buildtest:android ninja
